version: '3'
services:
  mysql_db:
    image: mysql
    container_name: airbnb_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_airbnb
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
    command:
        sh -c "mysql -uroot -p1234 db_airbnb | mysql -h54.179.228.27 -uroot -p1234 db_airbnb"
  app:
    depends_on:
      - mysql_db
    build: .
    container_name: container-node
    env_file: .env
    environment:
      - DB_HOST=mysql_db
      - DB_DIALECT=mysql
      - DB_NAME=db_airbnb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=1234 
    ports:
      - "80:8080"
    networks:
      - node-network
volumes:
  mysql_db:
    driver: local
networks:
  node-network: